export const USER_HOLDING_API = 'USER_HOLDING_API';
export const USER_HOLDING_API_SUCCESS = 'USER_HOLDING_API_SUCCESS';
export const USER_HOLDING_API_FAILURE = 'USER_HOLDING_API_FAILURE';
export const USER_TOTAL_INVESTMENT = 'USER_TOTAL_INVESTMENT';
